graph TD;
  test_scripts --> subcommand_implementations;
  interactively_generated_README_for_this_project --> subcommand_implementations;
  interactively_generated_README_for_this_project --> test_scripts;
  interactively_generated_README_for_this_project --> connections_within_the_system;
  subcommand_help_implementation_status --> subcommand_implementations;
