#!/bin/bash

# TODO: populate file worklist with a list of work
cd $(dirname $0)
# walk through the console output and find lines which appear to have been completed already.
# remove them from the worklist and start processing each line.
gawk '
  ARGIND == 1 { done[$1] = 1 ; next }
  ARGIND > 1 && !done[$1] { print "./process-item", $1 }
' <( cat output.gz | gzip -d - | awk '/^PROCESING WORK ITEM/ {print $NF}' ) worklist |\
parallel
