#!/bin/bash

# overwrite main readme file
# for now while this is not running in a container, this will work
READMEFILE="$(pwd)/README.md"
echo "writing readme file $READMEFILE" >/dev/stderr
cd $(dirname $0)

function generate_readme {
  cat header.md 
  echo
  echo '```bash'
  ngram --help 
  echo '```'
  echo
  echo '# Test Run Output'
  echo
  echo '```'
  cat ../20240705000124-9769d8256b20e049b259/stdout.log
  echo '```'
  echo
  cat footer.md
}

generate_readme | ngram replace "$READMEFILE"

wc -l "$READMEFILE"
