#!/bin/bash

export ngram_run_dir="$(pwd)"
export ngram_script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export ngram_cli_path="$(realpath $0)"
export ngram_root_dir=$(realpath "$ngram_cli_path/../../..")
export ngram_prog="$ngram_root_dir/ngram"
export PATH="$PATH:$ngram_root_dir"

# constants
export ngram_program_id="20240704164832-ae846f0d186e581bb7aa"
export ngram_subcommands_dir="$ngram_root_dir/database/$ngram_program_id/subcommands"

command="$1"
shift
if [ -z "$command" ]; then
  echo missing command
  exit 1
fi

command_prog="$ngram_subcommands_dir/$command"

if [[ "$command" =~ -h|--help ]]; then
  echo "Usage: $(basename $0)  [subcommand] [--help | options... ]"
  echo "Subcommands:"
  ls "$ngram_subcommands_dir"
  exit 1
elif [ ! -x "$command_prog" ]; then
  if [ "$command" = "ls" ]; then
    command="list"
  else
    echo "error no_subcommand $command" >/dev/stderr
    exit 1
  fi
  command_prog="$ngram_subcommands_dir/$command"
fi

cd $ngram_root_dir

if [ -f .env ]; then
  source .env
fi

"$command_prog" "$@"

#arglistf=$(mktemp)
#rm "$arglistf" # clean up argument list
#touch database/20240704164832-ae846f0d186e581bb7aa/subcommands/id
#touch database/20240704164832-ae846f0d186e581bb7aa/subcommands/create
#chmod +x database/20240704164832-ae846f0d186e581bb7aa/subcommands/id
#chmod +x database/20240704164832-ae846f0d186e581bb7aa/subcommands/create
