#!/bin/bash

# test changing the title
failed=0
id=$(./ngram create -t title1)
dir="database/$id"
readme="$dir/README.md"
echo test content >> $readme # add content to the readme to test overwriting the title

# test changing the title
./ngram set-title -t 'title2' $id
if ! grep '^# title2' $readme; then
  echo failed to change title
  fail=1
fi
if ! grep 'test content' $readme; then
  echo content erased - fail
  fail=1
fi

printf "## fake h2 file\n\n- line of content here\n" > $readme
cat $readme
./ngram set-title -t 'title3' $id
if ! grep '^#* title3' $readme; then
  echo failed to change title of h2
  fail=1
fi

rm -rf "$dir" # clean up directories created for test

exit $failed
