#!/bin/bash

# here is the logic to determine what files get scanned for changes
# gz files cannot be included in checksums because the data does not seem to be deterministic across machines and versions
# TODO: make sure it's clear that if gzip files are output, you should print stats about them like line counts to stdout so updates get triggered downstream otherwise updates to gz files get ignored

find database -type f | awk '
/\.mp4$/ { next }
/\.webm$/ { next }
/\.png$/ { next }
/\.gif$/ { next }
/\.gz$/ { next }
{ print }
' | xargs md5sum
