#!/bin/bash

# parse args with case statement
VERBOSE=0
title=""
while [[ $# -gt 0 ]]; do
  case $1 in
    -t|--title) # set title in README of created data point
      shift # pop arg
      title="$1"
      ;;
    -c|--clone) # clone from a template data point ID, bringing over all its files
      shift
      cloneid="$1"
      ;;
    -v|--verbose)
      VERBOSE=1
      ;;
    -h|--help)
      echo "Usage: $0 [ options ] directory"
      echo "Options:"
      cat "$0" | grep '^\s\+-.|--.*'
      exit 1
      ;;
  esac
  shift
done
# TODO: template argument - pass in id to copy for template

id=$("$ngram_prog" id)
dir="$ngram_root_dir/database/$id"

if [ ! -z "$cloneid" ]; then # if there's a template ID to clone from
  cp -r "$ngram_root_dir/database/$cloneid" "$dir"
  # TODO: check ID
else
  mkdir -p "$dir"
fi

if [ -z "$title" ]; then
  title="data point created at $(date)"
fi

"$ngram_prog" set-title -t "$title" "$id"

echo "$id"
echo "$dir" >/dev/stderr
