#!/bin/bash

tag="$1"
id="$2"
showhelp=0
if [ -z "$tag" ]; then
  showhelp=1
fi
if [ -z "$id" ]; then
  showhelp=1
fi
if [ "$tag" == "--help" ]; then
  showhelp=1
fi
if [ "$showhelp" = "1" ]; then
  echo usage $ngram_prog hastag tagquery 20240704164832-ae846f0d186e581bb7aa
  exit 1
fi
tagfile="database/$id/tags"
if grep "$tag" "$tagfile" >/dev/null 2>/dev/null; then
  echo yes
  exit 0
else
  echo no
  exit 1
fi
