#!/bin/bash

# create a loose link from one ngram directory to another.
# do this by adding a valid markdown link to the directory to the README file.

from="$1"
to="$2"
if [ -z "$from" ]; then
  echo missing to argument '#1'
  exit 1
fi
if [ -z "$to" ]; then
  echo missing to argument '#2'
  exit 1
fi
linkfile="database/$from/README.md"
echo "- [Ngram Linked ID $to](/database/$to)" >> "$linkfile"
