#!/bin/bash

if [ -z "$1" ]; then
  echo missing argument >/dev/stderr
fi
grep -Eof <(ls database | grep -v "$1") $("$ngram_prog" find-executable "database/$1" -type f) | cut -d : -f 2 #| awk -F / '{print $2}' | sort -u
