#!/bin/bash

# find refs by ID
# pass --all as parameter to get table of all refs
if [ -z "$1" ]; then
  echo missing argument >/dev/stderr
fi
exelist=$(mktemp)
"$ngram_prog" find-executable "database/$1" -type f > "$exelist"

if [ -s "$exelist" ]; then
  while [ ! -z "$1" ]; do
    if [ "$1" = "--all" ]; then
      grep -Eof <(ls database) $(cat $exelist) | awk -F : '
        BEGIN{OFS=" "}
        {
          gsub(/^database./,"",$1)
          gsub(/\/.*/,"",$1)
        }
        $1 != $2 && !seen[$1,$2] { print $1, $2 }
        { seen[$1,$2] = 1 }
      '
    else
      grep -Eof <(ls database | grep -v "$1") $(cat "$exelist") | cut -d : -f 2 | sort -u #| awk -F / '{print $2}' | sort -u
    fi
    shift # pop arg from arg list
  done
fi
rm "$exelist"
