#!/bin/bash

# utility subcommand to replace a file.
# use this when possible instead of shell redirection to avoid overwriting files until the program is complete.
# example: echo ... | ngram replace datafile.dat

if [ -z "$1" ]; then
  echo file argument required
  exit 1
fi
tf=$(mktemp)
if [ -z "$tf" ]; then
  echo failed to create temp file for replace swap >/dev/stderr
  exit 1
fi
cat > $tf
mv "$tf" "$1"
