#!/bin/bash

# entrypoint to run one single cycle of ngram.
# one cycle is defined as one pass over all IDs with programs that have dependencies that have changed since the last time the program was run.
# returns a status code of 1 if nothing was run
if [ "$1" == "--until-stable" ]; then
  while [ 1 ]; do
    echo Looping $(date)
    "$ngram_prog" run --single
    if [ "$?" != "0" ]; then
      exit 0
    fi
  done
elif [ "$1" = "--run-all" ]; then
  find database -name .ngram.dependencies.hashes | xargs rm # clear all hashes of all elements
elif [ -z "$1" ]; then # base case - no parameter given, run
  find $("$ngram_prog" query @live dirs) -name .ngram.dependencies.hashes | xargs rm # clear all hashes of live elements
  "$ngram_prog" run --until-stable
else # run single
  echo "running single stage at $(date)" >/dev/stderr
fi

didntrunanything=1

# run all IDs in topological order
for id in $( "$ngram_prog" find-executable database -type f -name run | awk -F / 'NF == 3 { print $2 }' | sort -u | xargs "$ngram_prog" tsort); do
  if ! "$ngram_prog" hastag template "$id"; then
    "$ngram_prog" run-single "$id"
    if [ "$?" = "0" ]; then
      didntrunanything=0
    fi
  fi
done

exit $didntrunanything
