#!/bin/bash

MAX_LOOP_INTERVAL=10
MIN_LOOP_INTERVAL=10
interval=1
while [ 1 ]; do
  echo "Looping $(date)"
  "$ngram_prog" run
  if [ "$?" = "0" ]; then
    interval=$MIN_LOOP_INTERVAL
  else
    interval=$(( interval + 1 )) # ramp up
    if [ $interval -gt $MAX_LOOP_INTERVAL ]; then
      interval=$MAX_LOOP_INTERVAL
    fi
  fi
  sleep $interval
done
