#!/bin/bash

# do a topological sort of the input IDs based on their dependencies between them
# or do a tsort of input IDs for all dependencies of changed things?!
inputids=$(mktemp)
if [ ! -z "$1" ]; then
  while [ ! -z "$1" ]; do
    echo "$1" >> $inputids
    shift
  done
else
  cat > $inputids # read from stdin
fi

#echo "Input IDs:" >>/dev/stderr
#cat $inputids >>/dev/stderr
export extras=$(mktemp) # temp file to list extra ids
cat $inputids | awk '
{
  command = ENVIRON["ngram_prog"] " findrefsto " $1
  printed = 0
  while ((command | getline ref) > 0) {
    print $1, ref
    printed = 1
    printedId[$1] = 1
    printedId[ref] = 1
  }
  close(command)
  if (!printed) {
    remainders[$1] = 1
  }
}
END {
  for (id in remainders) {
    if (!printedId[id]) {
      print id > ENVIRON["extras"]
    }
  }
}
' | gawk '
NF == 1 { hasid[$1] = 1 }
NF > 1 && hasid[$1] && hasid[$2] { print }
' $inputids /dev/stdin | "$ngram_prog" replace "$inputids"
#cat $inputids >/dev/stderr
cat "$extras"
tsort "$inputids"

rm "$extras"
rm "$inputids"
