#!/bin/bash

allarguments="$1" # the whole argument line from FZF comes in as one command

selectedcmd=$(echo "$1" | awk '{ print $1 }')
selecteddoc=$(echo "$1" | awk '{ print $NF }')

if [ -z "$DOC" ]; then
  echo "missing DOC environ var" >/dev/stderr
  exit 1
fi

# specify if this should show the original document or a different one
select=0

if [ "$selectedcmd" = "GOTO" ]; then
  select=1
elif [ "$selectedcmd" = "EDIT" ]; then
  select=1
elif [ "$selectedcmd" = "EDITCLIP" ]; then
  tmux saveb - # print tmux clipboard
  exit 0
elif [ "$selectedcmd" = "SAVECLIP" ]; then
  tmux saveb - # print tmux clipboard
  exit 0
elif [ "$selectedcmd" = "RUNBATCH" ]; then
  echo Batch Run
  ngram tsort $(ngram ls)
  exit 0
elif [ "$selectedcmd" = "GIT" ]; then
  git status
  exit 0
elif [ "$selectedcmd" = "DIAG" ]; then
  env
  exit 0
fi

echo Current Document: "$DOC"
echo Previewing: "$selecteddoc"
if [ "$select" = 0 ]; then
  bat --color=always "$DOC"
else
  bat --color=always "$selecteddoc"
fi
